name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout BE
        uses: actions/checkout@main
        with:
          repository: KDale119/plants-app
          path: './plant-be'
      - name: Checkout FE
        uses: actions/checkout@main
        with:
          repository: KDale119/plants-app-FE
          path: './plant-fe'
      - name: Use Node.js 20.x
        uses: actions/setup-node@main
        with:
          node-version: 20.x
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install and build frontend
        working-directory: ./plant-fe
        run: |
          npm install && npm run build
      - name: Copy FE files to resources
        working-directory: ./plant-fe/out
        run: |
          mkdir ../../plant-be/src/main/resources/static
          cp -r * ../../plant-be/src/main/resources/static
      - name: Build
        working-directory: ./plant-be
        run: mvn clean install
      - name: Login to Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker
        working-directory: ./plant-be
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/mcc-plant-app .
      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/mcc-plant-app:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/mcc-plant-app:latest
      - name: Remove Container
        run: sudo docker rm -f crud-application
      - name: Run Container
        run: sudo docker run -d -p 8080:8080 --name crud-application ${{secrets.DOCKER_USERNAME}}/mcc-plant-app:latest